### PR TITLE
[UI]:fixed home page ui 

### PR DESCRIPTION
**Pull request by imkuldeepahlawat**
Before

Screenshot from 2024-07-07 17-43-13

Screenshot from 2024-07-07 17-43-40
035/2b76b70e-04f9-4765-bbfd-130f3b3028ce)

After
Screenshot from 2024-07-07 17-41-12

### CODE REVIEW

**Comment by rohansh-tty** [comment]
type issue found in Login.tsx. Run `npm run build` and check the issue

**Review by rohansh-tty — COMMENTED** [review]
need to fix type issue in Login.tsx

**Comment by imkuldeepahlawat** [comment]
solved typescript issue in build

**Comment by imkuldeepahlawat** [comment]
Update!!

**Pull request merged**
